application: jsontoclass
version: 1
runtime: php55
api_version: 1

handlers:

- url: /download\.php
  script: download.php

  

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)
  
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)
  

- url: /.*
  script: index.html
